<?php
/**
 * TL_ROOT/system/modules/dlstats/languages/it/modules.php 
 * 
 * TYPOlight extension: dlstats 0.3.1 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2007, 2008 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Angelo Galleja (ga.n) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['dlstats']['0'] = "Statistiche Download";
$GLOBALS['TL_LANG']['MOD']['dlstats']['1'] = "Statistiche Download.";
 
?>
