<?php
/**
 * TL_ROOT/system/modules/dlstats/languages/it/tl_dlstats.php 
 * 
 * TYPOlight extension: dlstats 0.3.1 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2007, 2008 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Angelo Galleja (ga.n) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_dlstats']['tstamp']['0'] = "Ultimo download";
$GLOBALS['TL_LANG']['tl_dlstats']['tstamp']['1'] = "Data e ora dell'ultimo download.";
$GLOBALS['TL_LANG']['tl_dlstats']['downloads']['0'] = "Totale download";
$GLOBALS['TL_LANG']['tl_dlstats']['downloads']['1'] = "Totale download effettuati.";
$GLOBALS['TL_LANG']['tl_dlstats']['filename']['0'] = "Nome del file";
$GLOBALS['TL_LANG']['tl_dlstats']['filename']['1'] = "Nome del file scaricato.";
$GLOBALS['TL_LANG']['tl_dlstats']['edit']['0'] = "Modifica";
$GLOBALS['TL_LANG']['tl_dlstats']['edit']['1'] = "Modifica questa statistica.";
$GLOBALS['TL_LANG']['tl_dlstats']['delete']['0'] = "Elimina";
$GLOBALS['TL_LANG']['tl_dlstats']['delete']['1'] = "Elimina questa statistica";
$GLOBALS['TL_LANG']['tl_dlstats']['details']['0'] = "Dettagli";
$GLOBALS['TL_LANG']['tl_dlstats']['details']['1'] = "Visualizza i dettagli dei download.";
 
?>
