<?php
/**
 * TL_ROOT/system/modules/dlstats/languages/it/tl_dlstatdets.php 
 * 
 * TYPOlight extension: dlstats 0.3.1 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2007, 2008 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Angelo Galleja (ga.n) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_dlstatdets']['tstamp']['0'] = "Timestamp";
$GLOBALS['TL_LANG']['tl_dlstatdets']['tstamp']['1'] = "Data e ora del download";
$GLOBALS['TL_LANG']['tl_dlstatdets']['ip']['0'] = "IP";
$GLOBALS['TL_LANG']['tl_dlstatdets']['ip']['1'] = "Indirizzo IP dell'utente";
$GLOBALS['TL_LANG']['tl_dlstatdets']['username']['0'] = "Username";
$GLOBALS['TL_LANG']['tl_dlstatdets']['username']['1'] = "Username dell'utente (se ha effettuato il login)";
$GLOBALS['TL_LANG']['tl_dlstatdets']['delete']['0'] = "Elimina";
$GLOBALS['TL_LANG']['tl_dlstatdets']['delete']['1'] = "Elimina questo record.";
 
?>
