<?php
/**
 * TL_ROOT/system/modules/dlstats/languages/it/tl_settings.php 
 * 
 * TYPOlight extension: dlstats 0.3.1 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; 2007, 2008 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Angelo Galleja (ga.n) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['dlstats']['0'] = "Abilita statistiche dei download";
$GLOBALS['TL_LANG']['tl_settings']['dlstats']['1'] = "Seleziona per abilitare il conteggio dei download";
$GLOBALS['TL_LANG']['tl_settings']['dlstatdets']['0'] = "Abilita statistiche dettagliate dei download";
$GLOBALS['TL_LANG']['tl_settings']['dlstatdets']['1'] = "Seleziona per tenere traccia di ogni singolo download.";
 
?>
