<?php
/**
 * TL_ROOT/system/modules/dlstats/languages/ru/modules.php 
 * 
 * Contao extension: dlstats 1.0.0 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2007-2009 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Dmitri Kuznetsov (kuzmich), http://www.onfreedom.ru 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['dlstats']['0'] = "Статистика загрузок";
$GLOBALS['TL_LANG']['MOD']['dlstats']['1'] = "Статистика загрузок с сайта.";
 
?>
