<?php
/**
 * TL_ROOT/system/modules/dlstats/languages/ru/tl_dlstats.php 
 * 
 * Contao extension: dlstats 1.0.0 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2007-2009 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Dmitri Kuznetsov (kuzmich), http://www.onfreedom.ru 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_dlstats']['tstamp']['0'] = "Последняя загрузка";
$GLOBALS['TL_LANG']['tl_dlstats']['tstamp']['1'] = "Дата и время последней загрузки.";
$GLOBALS['TL_LANG']['tl_dlstats']['downloads']['0'] = "Всего загрузок";
$GLOBALS['TL_LANG']['tl_dlstats']['downloads']['1'] = "Общее количество загрузок.";
$GLOBALS['TL_LANG']['tl_dlstats']['filename']['0'] = "Имя файла";
$GLOBALS['TL_LANG']['tl_dlstats']['filename']['1'] = "Имя загружаемого файла.";
$GLOBALS['TL_LANG']['tl_dlstats']['edit']['0'] = "Редактировать";
$GLOBALS['TL_LANG']['tl_dlstats']['edit']['1'] = "Редактировать этот файл статистики.";
$GLOBALS['TL_LANG']['tl_dlstats']['delete']['0'] = "Удалить";
$GLOBALS['TL_LANG']['tl_dlstats']['delete']['1'] = "Удалить этот файл статистики.";
$GLOBALS['TL_LANG']['tl_dlstats']['details']['0'] = "Детали";
$GLOBALS['TL_LANG']['tl_dlstats']['details']['1'] = "Посмотреть детали о загрузках.";
 
?>
