<?php
/**
 * TL_ROOT/system/modules/dlstats/languages/ru/tl_dlstatdets.php 
 * 
 * Contao extension: dlstats 1.0.0 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2007-2009 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Dmitri Kuznetsov (kuzmich), http://www.onfreedom.ru 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_dlstatdets']['tstamp']['0'] = "Временная метка";
$GLOBALS['TL_LANG']['tl_dlstatdets']['tstamp']['1'] = "Дата и время загрузки.";
$GLOBALS['TL_LANG']['tl_dlstatdets']['ip']['0'] = "IP-адрес";
$GLOBALS['TL_LANG']['tl_dlstatdets']['ip']['1'] = "IP-адрес загружавшего.";
$GLOBALS['TL_LANG']['tl_dlstatdets']['username']['0'] = "Имя пользователя";
$GLOBALS['TL_LANG']['tl_dlstatdets']['username']['1'] = "Имя пользователя зарегистрированного на сайте, если он вошел.";
$GLOBALS['TL_LANG']['tl_dlstatdets']['delete']['0'] = "Удалить";
$GLOBALS['TL_LANG']['tl_dlstatdets']['delete']['1'] = "Удалить эту запись.";
 
?>
