<?php
/**
 * TL_ROOT/system/modules/dlstats/languages/ru/tl_dlstats.php 
 * 
 * Contao extension: dlstats 3.7.0 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2011..2014 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Dmitri Kuznetsov (kuzmich), http://www.onfreedom.ru 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_dlstats']['no_key'] = "Не указан путь/имя файла (параметр 2)";
$GLOBALS['TL_LANG']['tl_dlstats']['wrong_key'] = "Поврежденное или некорректное имя тега (параметр 1)";
 
?>
