<?php
/**
 * TL_ROOT/system/modules/dlstats/languages/ru/tl_settings.php 
 * 
 * Contao extension: dlstats 1.0.0 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2007-2009 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Dmitri Kuznetsov (kuzmich), http://www.onfreedom.ru 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['dlstats_legend'] = "Статистика загрузок";
$GLOBALS['TL_LANG']['tl_settings']['dlstats']['0'] = "Включить статистику загрузок";
$GLOBALS['TL_LANG']['tl_settings']['dlstats']['1'] = "Отметьте для включения подсчета количества загрузок.";
$GLOBALS['TL_LANG']['tl_settings']['dlstatdets']['0'] = "Включить детализированную статистику загрузок";
$GLOBALS['TL_LANG']['tl_settings']['dlstatdets']['1'] = "Отметьте для включения журналирования всей информации о загрузках.";
 
?>
