<?php
/**
 * TL_ROOT/system/modules/dlstats/languages/ru/tl_settings.php 
 * 
 * Contao extension: dlstats 3.7.0 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2011..2014 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Dmitri Kuznetsov (kuzmich), http://www.onfreedom.ru 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['dlstats_legend'] = "Статистика загрузок";
$GLOBALS['TL_LANG']['tl_settings']['dlstats']['0'] = "Включить статистику загрузок";
$GLOBALS['TL_LANG']['tl_settings']['dlstats']['1'] = "Выберите для включения подсчета количества загрузок.";
$GLOBALS['TL_LANG']['tl_settings']['dlstats']['anonip4']['1'] = "Октеты: 1 (по умолчанию Contao)";
$GLOBALS['TL_LANG']['tl_settings']['dlstats']['anonip4']['2'] = "Октеты: 2";
$GLOBALS['TL_LANG']['tl_settings']['dlstats']['anonip6']['2'] = "Группы: 2 (по умолчанию Contao)";
$GLOBALS['TL_LANG']['tl_settings']['dlstats']['anonip6']['3'] = "Группы: 3";
$GLOBALS['TL_LANG']['tl_settings']['dlstats']['anonip6']['4'] = "Группы: 4";
$GLOBALS['TL_LANG']['tl_settings']['dlstatdets']['0'] = "Включить детализированную статистику загрузок";
$GLOBALS['TL_LANG']['tl_settings']['dlstatdets']['1'] = "Выберите для начала журналирования всей информации о загрузках.";
$GLOBALS['TL_LANG']['tl_settings']['dlstatDisableBotdetection']['0'] = "Отключить фильтрацию обнаружения ботов";
$GLOBALS['TL_LANG']['tl_settings']['dlstatDisableBotdetection']['1'] = "Отключить фильтрацию обнаружения ботов модулем Bot Detection";
$GLOBALS['TL_LANG']['tl_settings']['dlstatAnonymizeIP4']['0'] = "Уровень анонимности для IPv4";
$GLOBALS['TL_LANG']['tl_settings']['dlstatAnonymizeIP4']['1'] = "Вы можете изменить уровень анонимности для IPv4. Функция 'Анонимизировать IP-адреса' в панели настроек Contao должна быть включена.";
$GLOBALS['TL_LANG']['tl_settings']['dlstatAnonymizeIP6']['0'] = "Уровень анонимности для IPv6";
$GLOBALS['TL_LANG']['tl_settings']['dlstatAnonymizeIP6']['1'] = "Вы можете изменить уровень анонимности для IPv6. Функция 'Анонимизировать IP-адреса' в панели настроек Contao должна быть включена.";
$GLOBALS['TL_LANG']['tl_settings']['dlstatTopDownloads']['0'] = "Количество элементов в ТОП загрузок";
$GLOBALS['TL_LANG']['tl_settings']['dlstatTopDownloads']['1'] = "Количество элементов в ТОП загрузок";
$GLOBALS['TL_LANG']['tl_settings']['dlstatLastDownloads']['0'] = "Количество элементов в последних загрузках";
$GLOBALS['TL_LANG']['tl_settings']['dlstatLastDownloads']['1'] = "Количество элементов в последних загрузках";
 
?>
