<?php
/**
 * TL_ROOT/system/modules/dlstats/languages/pl/tl_dlstats.php 
 * 
 * Contao extension: dlstats 1.0.0 stable 
 * Polish translation file 
 * 
 * Copyright : &copy; 2007-2009 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Tomasz Adamski (djtms), www.miastopiaseczno.pl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_dlstats']['tstamp']['0'] = "Ostatnie pobranie";
$GLOBALS['TL_LANG']['tl_dlstats']['tstamp']['1'] = "Data i czas ostatniego pobrania.";
$GLOBALS['TL_LANG']['tl_dlstats']['downloads']['0'] = "Wszystkie pobrania";
$GLOBALS['TL_LANG']['tl_dlstats']['downloads']['1'] = "Liczba wszystkich pobrań.";
$GLOBALS['TL_LANG']['tl_dlstats']['filename']['0'] = "Nazwa pliku";
$GLOBALS['TL_LANG']['tl_dlstats']['filename']['1'] = "Nazwa pobieranego pliku.";
$GLOBALS['TL_LANG']['tl_dlstats']['edit']['0'] = "Edytuj";
$GLOBALS['TL_LANG']['tl_dlstats']['edit']['1'] = "Edytuj statystyki tego pliku.";
$GLOBALS['TL_LANG']['tl_dlstats']['delete']['0'] = "Skasuj";
$GLOBALS['TL_LANG']['tl_dlstats']['delete']['1'] = "Skasuj statystyki tego pliku.";
$GLOBALS['TL_LANG']['tl_dlstats']['details']['0'] = "Szczegóły";
$GLOBALS['TL_LANG']['tl_dlstats']['details']['1'] = "Zobacz szczegóły pobrań.";
 
?>
