<?php
/**
 * TL_ROOT/system/modules/dlstats/languages/pl/tl_dlstatdets.php 
 * 
 * Contao extension: dlstats 1.0.0 stable 
 * Polish translation file 
 * 
 * Copyright : &copy; 2007-2009 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Tomasz Adamski (djtms), www.miastopiaseczno.pl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_dlstatdets']['tstamp']['0'] = "Data i czas";
$GLOBALS['TL_LANG']['tl_dlstatdets']['tstamp']['1'] = "Data i czas pobrania.";
$GLOBALS['TL_LANG']['tl_dlstatdets']['ip']['0'] = "IP";
$GLOBALS['TL_LANG']['tl_dlstatdets']['ip']['1'] = "IP pobierającego.";
$GLOBALS['TL_LANG']['tl_dlstatdets']['username']['0'] = "Nazwa członka";
$GLOBALS['TL_LANG']['tl_dlstatdets']['username']['1'] = "Członek serwisu.";
$GLOBALS['TL_LANG']['tl_dlstatdets']['delete']['0'] = "Skasuj";
$GLOBALS['TL_LANG']['tl_dlstatdets']['delete']['1'] = "Skasuj ten rekord.";
 
?>
