<?php
/**
 * TL_ROOT/system/modules/dlstats/languages/pl/tl_settings.php 
 * 
 * Contao extension: dlstats 1.0.0 stable 
 * Polish translation file 
 * 
 * Copyright : &copy; 2007-2009 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Tomasz Adamski (djtms), www.miastopiaseczno.pl 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['dlstats_legend'] = "statystyki pobierania";
$GLOBALS['TL_LANG']['tl_settings']['dlstats']['0'] = "Włącz statystyki pobrań";
$GLOBALS['TL_LANG']['tl_settings']['dlstats']['1'] = "Zaznacz aby włączyć zliczanie pobrań.";
$GLOBALS['TL_LANG']['tl_settings']['dlstatdets']['0'] = "Włącz szczegółowe statystyki pobrań";
$GLOBALS['TL_LANG']['tl_settings']['dlstatdets']['1'] = "Zaznacz aby włączyć logowanie wszystkich pobrań poszczególnych plików z serwisu.";
 
?>
