<?php
/**
 * TL_ROOT/system/modules/dlstats/languages/ja/tl_dlstats.php 
 * 
 * Contao extension: dlstats 3.7.0 stable 
 * Japanese translation file 
 * 
 * Copyright : &copy; 2011..2014 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_dlstats']['no_key'] = "パスやファイル名が未指定(第2引数)";
$GLOBALS['TL_LANG']['tl_dlstats']['wrong_key'] = "不完全または正しくないタグ名(第1引数)";
 
?>
