<?php
/**
 * TL_ROOT/system/modules/dlstats/languages/ja/tl_dlstats.php 
 * 
 * Contao extension: dlstats 1.0.0 stable 
 * Japanese translation file 
 * 
 * Copyright : &copy; 2007-2009 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_dlstats']['tstamp']['0'] = "最後のダウンロード";
$GLOBALS['TL_LANG']['tl_dlstats']['tstamp']['1'] = "最後のダウンロードの日付と時刻です。";
$GLOBALS['TL_LANG']['tl_dlstats']['downloads']['0'] = "ダウンロードの総計";
$GLOBALS['TL_LANG']['tl_dlstats']['downloads']['1'] = "ダウンロードの総計です。";
$GLOBALS['TL_LANG']['tl_dlstats']['filename']['0'] = "ファイル名";
$GLOBALS['TL_LANG']['tl_dlstats']['filename']['1'] = "ダウンロードされたファイルの名前です。";
$GLOBALS['TL_LANG']['tl_dlstats']['edit']['0'] = "変更";
$GLOBALS['TL_LANG']['tl_dlstats']['edit']['1'] = "このファイルの統計を変更します。";
$GLOBALS['TL_LANG']['tl_dlstats']['delete']['0'] = "削除";
$GLOBALS['TL_LANG']['tl_dlstats']['delete']['1'] = "このファイルの統計を削除します。";
$GLOBALS['TL_LANG']['tl_dlstats']['details']['0'] = "詳細";
$GLOBALS['TL_LANG']['tl_dlstats']['details']['1'] = "このダウンロードの詳細を表示します。";
 
?>
