<?php
/**
 * TL_ROOT/system/modules/dlstats/languages/ja/tl_dlstatdets.php 
 * 
 * Contao extension: dlstats 1.0.0 stable 
 * Japanese translation file 
 * 
 * Copyright : &copy; 2007-2009 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_dlstatdets']['tstamp']['0'] = "日時";
$GLOBALS['TL_LANG']['tl_dlstatdets']['tstamp']['1'] = "ダウンロードの日付と時刻です。";
$GLOBALS['TL_LANG']['tl_dlstatdets']['ip']['0'] = "IP";
$GLOBALS['TL_LANG']['tl_dlstatdets']['ip']['1'] = "ダウンロードしたIPアドレスです。";
$GLOBALS['TL_LANG']['tl_dlstatdets']['username']['0'] = "ユーザー名";
$GLOBALS['TL_LANG']['tl_dlstatdets']['username']['1'] = "ログインしていた場合、フロントエンドのメンバーのユーザー名です。";
$GLOBALS['TL_LANG']['tl_dlstatdets']['delete']['0'] = "削除";
$GLOBALS['TL_LANG']['tl_dlstatdets']['delete']['1'] = "このレコードを削除します。";
 
?>
