<?php
/**
 * TL_ROOT/system/modules/dlstats/languages/ja/tl_settings.php 
 * 
 * Contao extension: dlstats 1.0.0 stable 
 * Japanese translation file 
 * 
 * Copyright : &copy; 2007-2009 Peter Koch 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['dlstats_legend'] = "ダウンロードの統計";
$GLOBALS['TL_LANG']['tl_settings']['dlstats']['0'] = "回数を記録";
$GLOBALS['TL_LANG']['tl_settings']['dlstats']['1'] = "ダウロードの回数を記録します。";
$GLOBALS['TL_LANG']['tl_settings']['dlstatdets']['0'] = "詳細な統計を使用";
$GLOBALS['TL_LANG']['tl_settings']['dlstatdets']['1'] = "個々のダウンロードをすべて記録します。";
 
?>
