<?php
/**
 * TL_ROOT/system/modules/dlstats/languages/ja/tl_settings.php 
 * 
 * Contao extension: dlstats 3.7.0 stable 
 * Japanese translation file 
 * 
 * Copyright : &copy; 2011..2014 Glen Langer 
 * License   : LGPL 
 * Author    : Glen Langer (BugBuster), http://www.contao.glen-langer.de 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['dlstats_legend'] = "ダウンロードの統計";
$GLOBALS['TL_LANG']['tl_settings']['dlstats']['0'] = "回数を記録";
$GLOBALS['TL_LANG']['tl_settings']['dlstats']['1'] = "ダウロードの回数を記録します。";
$GLOBALS['TL_LANG']['tl_settings']['dlstats']['anonip4']['1'] = "オクテット: 1 (Contaoの初期設定)";
$GLOBALS['TL_LANG']['tl_settings']['dlstats']['anonip4']['2'] = "オクテット: 2";
$GLOBALS['TL_LANG']['tl_settings']['dlstats']['anonip6']['2'] = "グループ: 2 (Contaoの初期設定)";
$GLOBALS['TL_LANG']['tl_settings']['dlstats']['anonip6']['3'] = "グループ: 3";
$GLOBALS['TL_LANG']['tl_settings']['dlstats']['anonip6']['4'] = "グループ: 4";
$GLOBALS['TL_LANG']['tl_settings']['dlstatdets']['0'] = "詳細な統計を使用";
$GLOBALS['TL_LANG']['tl_settings']['dlstatdets']['1'] = "個々のダウンロードをすべて記録します。";
$GLOBALS['TL_LANG']['tl_settings']['dlstatDisableBotdetection']['0'] = "Bot検出のフィルタリングを無効";
$GLOBALS['TL_LANG']['tl_settings']['dlstatDisableBotdetection']['1'] = "Bot検出の機能拡張による計数のフィルタリングを無効にします。";
$GLOBALS['TL_LANG']['tl_settings']['dlstatAnonymizeIP4']['0'] = "IPv4の匿名化のレベル";
$GLOBALS['TL_LANG']['tl_settings']['dlstatAnonymizeIP4']['1'] = "IPv4の匿名化のレベルを調整できます。ContaoでIPアドレスの匿名化を有効にしなければなりません。";
$GLOBALS['TL_LANG']['tl_settings']['dlstatAnonymizeIP6']['0'] = "IPv6の匿名化のレベル";
$GLOBALS['TL_LANG']['tl_settings']['dlstatAnonymizeIP6']['1'] = "IPv6の匿名化のレベルを調整できます。ContaoでIPアドレスの匿名化を有効にしなければなりません。";
$GLOBALS['TL_LANG']['tl_settings']['dlstatTopDownloads']['0'] = "ダウンロードの上位の回数";
$GLOBALS['TL_LANG']['tl_settings']['dlstatTopDownloads']['1'] = "統計でダウンロードの上位の回数とする項目の数です。";
$GLOBALS['TL_LANG']['tl_settings']['dlstatLastDownloads']['0'] = "最近のダウンロードの上位の回数";
$GLOBALS['TL_LANG']['tl_settings']['dlstatLastDownloads']['1'] = "統計で最近のダウンロードの上位の回数とする項目の数です。";
 
?>
