<?php
/**
 * TL_ROOT/system/modules/dlstats/languages/fr/modules.php 
 * 
 * TYPOlight extension: dlstats 0.3.1 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2007, 2008 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['dlstats']['0'] = "Stats de téléchargements";
$GLOBALS['TL_LANG']['MOD']['dlstats']['1'] = "Statistiques de téléchargements.";
 
?>
