<?php
/**
 * TL_ROOT/system/modules/dlstats/languages/fr/tl_dlstatdets.php 
 * 
 * TYPOlight extension: dlstats 0.3.1 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2007, 2008 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_dlstatdets']['tstamp']['0'] = "Date et heure";
$GLOBALS['TL_LANG']['tl_dlstatdets']['tstamp']['1'] = "Date et heure du téléchargement.";
$GLOBALS['TL_LANG']['tl_dlstatdets']['ip']['0'] = "IP";
$GLOBALS['TL_LANG']['tl_dlstatdets']['ip']['1'] = "IP du client de téléchargement.";
$GLOBALS['TL_LANG']['tl_dlstatdets']['username']['0'] = "Nom d'utilisateur";
$GLOBALS['TL_LANG']['tl_dlstatdets']['username']['1'] = "Nom du membre, si connecté.";
$GLOBALS['TL_LANG']['tl_dlstatdets']['delete']['0'] = "Supprimer";
$GLOBALS['TL_LANG']['tl_dlstatdets']['delete']['1'] = "Supprimer cet enregistrement.";
 
?>
