<?php
/**
 * TL_ROOT/system/modules/dlstats/languages/fr/tl_dlstats.php 
 * 
 * TYPOlight extension: dlstats 0.3.1 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2007, 2008 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_dlstats']['tstamp']['0'] = "Dernier téléchargement";
$GLOBALS['TL_LANG']['tl_dlstats']['tstamp']['1'] = "Date et heure du dernier téléchargement.";
$GLOBALS['TL_LANG']['tl_dlstats']['downloads']['0'] = "Total des téléchargements";
$GLOBALS['TL_LANG']['tl_dlstats']['downloads']['1'] = "Nombre total de téléchargements.";
$GLOBALS['TL_LANG']['tl_dlstats']['filename']['0'] = "Fichier";
$GLOBALS['TL_LANG']['tl_dlstats']['filename']['1'] = "Nom du fichier téléchargé.";
$GLOBALS['TL_LANG']['tl_dlstats']['edit']['0'] = "Editer";
$GLOBALS['TL_LANG']['tl_dlstats']['edit']['1'] = "Editer ce fichier de statistiques.";
$GLOBALS['TL_LANG']['tl_dlstats']['delete']['0'] = "Supprimer";
$GLOBALS['TL_LANG']['tl_dlstats']['delete']['1'] = "Supprimer ce fichier de statistiques.";
$GLOBALS['TL_LANG']['tl_dlstats']['details']['0'] = "Détails";
$GLOBALS['TL_LANG']['tl_dlstats']['details']['1'] = "Afficher le détail des téléchargements.";
 
?>
