<?php
/**
 * TL_ROOT/system/modules/dlstats/languages/fr/tl_settings.php 
 * 
 * TYPOlight extension: dlstats 0.3.1 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2007, 2008 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['dlstats']['0'] = "Activer les statistiques des téléchargements";
$GLOBALS['TL_LANG']['tl_settings']['dlstats']['1'] = "Cocher pour activer le compteur de téléchargements.";
$GLOBALS['TL_LANG']['tl_settings']['dlstatdets']['0'] = "Activer les statistiques détaillées";
$GLOBALS['TL_LANG']['tl_settings']['dlstatdets']['1'] = "Cocher pour journaliser chaque téléchargement selon l'identifiant de connexion.";
 
?>
